[workspace]
members = ["bindgen", "bridge", "cli", "ffi", "lib", "net", "rand", "scoped_task", "util", "vfs"]

[workspace.package]
version = "0.5.1"
authors = ["Adam Cigánek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
repository = "https://github.com/equalitie/ouisync"
license = "MPL-2.0"
edition = "2021"
rust-version = "1.65.0"

[workspace.dependencies]
async-trait = "0.1.64"
btdht = { git = "https://github.com/equalitie/btdht.git", rev = "5287b4a2bc507cde87903bc30ca2f1c548a31e18" }
futures-util = { version = "0.3.21", default-features = false }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_bytes = "0.11.8"
thiserror = "1.0.31"
tokio = { version = "1.24.1", default-features = false }
tokio-stream = "0.1.9"
tokio-util = "0.7.4"
tracing = { version = "0.1.35" }
tracing-subscriber = { version = "0.3.15" }
turmoil = { git = "https://github.com/tokio-rs/turmoil" }
sqlx = { path = "/home/peter/work/sqlx", default-features = false, features = ["runtime-tokio-rustls", "sqlite"]  }

[profile.bench]
# Enable debug info so we can profile the benches
debug = 1

[patch.crates-io]
# Contains latest sqlite which seems to fix some bugs that were affecting us
sqlx = { git = "https://github.com/madadam/sqlx.git", branch = "bump-libsqlite3-sys" }
